plugins {
    id 'com.android.application'
}

android {
    namespace 'com.j8keyswap'
    compileSdk 34

    defaultConfig {
        applicationId 'com.j8keyswap'
        minSdk 21
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
